app.author.1 = Allyssa May Cristino
app.author.2 = Joshua Fildam Christopher Chu
app.author.3 = Dizahlene Catenza
app.author.4 = Matt Lenard Laraga
app.version = JDK.25
app.java_version = 25 (build 25+37-LTS-3491)
app.environment = Packaged with Java(TM) SE Runtime Environment
app.distribution = JAR with installer 
